# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
pesde = "pesde-pkg/pesde@0.6.2+registry.0.2.2"
lune = "lune-org/lune@0.8.9"
